name: Matillion to dbt Cloud Workflow

# Trigger manually or on push to 'main' branch with changes in matillion_dbt_pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'matillion_dbt_pipeline/**'

jobs:
  trigger_dbt_cloud:
    name: Trigger dbt Cloud Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # ===============================
      # MATILLION STEP (Commented Out)
      # ===============================
      # - name: Trigger Matillion Job
      #   run: |
      #     curl -X POST "https://<your-matillion-url>/rest/v1/group/name/job/name/run" \
      #     -H "Authorization: Bearer ${{ secrets.MATILLION_TOKEN }}" \
      #     -H "Content-Type: application/json" \
      #     -d '{}'
      #   # NOTE:
      #   # - Replace <your-matillion-url> with your Matillion API endpoint.
      #   # - Store your Matillion API token in GitHub Secrets as MATILLION_TOKEN.

      # ===============================
      # DBT CLOUD STEP
      # ===============================

      # Step 2: Trigger dbt Cloud job using API
      - name: Trigger dbt Cloud Job
        run: |
          curl -X POST https://cloud.getdbt.com/api/v2/accounts/${{ secrets.DBT_ACCOUNT_ID }}/jobs/${{ secrets.DBT_JOB_ID }}/run/ \
          -H "Authorization: Token ${{ secrets.DBT_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
        # Uses dbt Cloud API v2 to trigger the job run.
        # Make sure secrets DBT_ACCOUNT_ID, DBT_JOB_ID, and DBT_API_TOKEN are set.

      # Step 3: Print confirmation message
      - name: Confirm Trigger
        run: echo "✅ dbt Cloud job has been triggered!"
