name: Terraform Workflow

on:
  push:
    branches:
      - main         # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main         # Trigger on PRs to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0  # Specify the version you want to use

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="dev.tfvars"

    - name: Terraform Apply
      if: github.event_name == 'push'  # Only apply on push to main
      run: terraform apply -var-file="dev.tfvars" -auto-approve

    - name: Terraform Output
      run: terraform output
